services:  
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cliente
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-proot"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 10s
  server:
    build:
      context: .
      target: final
    ports:
      - 5106:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Port=3307;Database=cliente;User=root;Password=root;
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  db-data:
